### If you can read this, I'm khaled, the port number (7151) is mine, yours may be different :)
@VehicleExplorer.Api_HostAddress =   https://localhost:7151

###=========================================== Original APIs ===========================================
### Get all makes

GET https://vpic.nhtsa.dot.gov/api/vehicles/GetAllMakes?format=json
Accept: application/json


### Get vehicle types for make

GET https://vpic.nhtsa.dot.gov/api/vehicles/GetVehicleTypesForMakeId/448?format=json
Accept: application/json


### Get models for make + year + vehicle type

GET https://vpic.nhtsa.dot.gov/api/vehicles/GetModelsForMakeIdYear/makeId/474/modelyear/2015/vehicletype/truck?format=json
Accept: application/json


###=========================================== Our New Application APIs ===========================================
### Get all vehicle makes

GET {{VehicleExplorer.Api_HostAddress}}/api/makes
Accept: application/json


### Get vehicle types for Honda

GET {{VehicleExplorer.Api_HostAddress}}/api/makes/448/vehicle-types
Accept: application/json